{"name": "Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x00000145C4E8F680>\ncourier_login_valid_creds = ({'firstName': 'kjlpmtx2uk', 'login': 't6r2obavm9', 'password': 'cndfinrmtz'}, 292926)\n\n    @allure.title('Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_empty_order_id_fail(\n            self,\n            courier_login_valid_creds,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        resp = order_helpers.accept_order(\n            None,\n            courier_id,\n        )\n>       assert resp.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\orders\\test_accept_order.py:53: AssertionError"}, "steps": [{"name": "Принять заказ с id None курьером с courier_id 292926", "status": "passed", "parameters": [{"name": "order_id", "value": "None"}, {"name": "courier_id", "value": "292926"}], "start": 1713160246273, "stop": 1713160246589}], "start": 1713160246273, "stop": 1713160246590, "uuid": "408f501f-07f1-4d83-8624-64dff975b662", "historyId": "415d6c569ef8bcfc87ae2de00af7174c", "testCaseId": "415d6c569ef8bcfc87ae2de00af7174c", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_empty_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "25024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}