{"name": "Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x000001ADE2D57470>\ncourier_login_valid_creds = ({'firstName': 'ail6qoq87t', 'login': 'wv2blqc0l5', 'password': '9446lbtv6m'}, 288065)\n\n    @allure.title('Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_empty_order_id_fail(\n            self,\n            courier_login_valid_creds,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        resp = order_helpers.accept_order(\n            None,\n            courier_id,\n        )\n>       assert resp.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\orders\\test_accept_order.py:52: AssertionError"}, "start": 1712509319130, "stop": 1712509319407, "uuid": "2e79e084-bc7d-4293-9363-691712d92a9e", "historyId": "415d6c569ef8bcfc87ae2de00af7174c", "testCaseId": "415d6c569ef8bcfc87ae2de00af7174c", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_empty_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "35896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}